package com.webDataProject.webData;

import java.util.List;
import java.util.Date;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import com.webDataProject.webData.UserRepository;
import org.springframework.web.bind.annotation.PathVariable;
@Controller
@RequestMapping("/api")
public class LandingController {
	@Autowired // This means to get the bean called userRepository Which is auto-generated by Spring, 
				// we will use it to handle the data
	private UserRepository userRepository;
	
	@GetMapping("/index")
	public String greeting() {
		return "index";
	}
	@GetMapping("/all")
  	public @ResponseBody Iterable<User> getAllUsers() {
	  // This returns a JSON or XML with the users
	  return userRepository.findAll();
    }
	
	@GetMapping("/stocks/{ticker}")
	public @ResponseBody List<User> getDataByTicker(@PathVariable String ticker) {
	     return userRepository.findByTicker(ticker);
	}
	@GetMapping("/stocks/date/{day}")
	public @ResponseBody List<User> getDataByDay(@PathVariable String day) {
	    return userRepository.findByDate(day);
	}
	@GetMapping("/stocks/{ticker}/{day}")
	public @ResponseBody List<User> getDataByDay(@PathVariable String day, @PathVariable String ticker) {
	    return userRepository.findByDateAndTicker(day, ticker);
	}
	@GetMapping("/stocks/{ticker}/{startDate}/{endDate}")
	// Mapping wants dates in yyyy-mm-dd format
	public @ResponseBody List<User> getTickerSpecificData(@PathVariable String ticker, @PathVariable String startDate, @PathVariable String endDate){
		return userRepository.getAllBetweenDatesAndTicker(ticker, startDate, endDate);
	}
}